<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

/**
 * Not run via `db:seed` (it has no mitra to attach rows to). This is a plain
 * data source consumed by AkuntansiCoaService::seedForMitra(), which copies
 * template() into a specific mitra's akuntansi_accounts rows.
 *
 * Extracted verbatim from `AKUNTANSI - CAFE LALLO KENDARI - SAMPLE - ooka
 * (1).xlsx`, sheet COA (196 rows), with two corrections to source data-entry
 * errors in that workbook:
 * - Code 40114 was duplicated for both 'PENDAPATAN LAIN-LAIN' (active) and
 *   'PENDAPATAN LABA' (inactive) — the second was renumbered to the next
 *   free leaf slot, 40115.
 * - 17 rows under KEWAJIBAN LANCAR had a blank account code (broken
 *   #REF! formulas in the source spreadsheet) and were dropped entirely —
 *   there was no way to recover their intended code/name.
 *
 * `parent_code` is derived by truncating the 5-digit leaf code to its
 * 3/4-digit group prefix. The source workbook's own group numbering has a
 * few irregular jumps (e.g. some leaf rows' 4-digit prefix doesn't match
 * any group-header row's code), inherited as-is here — this only affects
 * cosmetic COA tree grouping in the UI, never account_type/position/
 * system_role, which come straight from the sheet's own JENIS AKUN/POSISI
 * AKUN columns and drive all posting/reporting logic.
 */
class AkuntansiCoaTemplateSeeder extends Seeder
{
    public function run(): void
    {
        // Intentionally empty — see class docblock.
    }

    /**
     * @return array<int, array{code: string, parent_code: ?string, name: string, level: int, account_type: ?string, position: ?string, is_postable: bool, system_role: ?string, is_active: bool}>
     */
    public static function template(): array
    {
        return [
            ['code' => '101', 'parent_code' => null, 'name' => 'ASET LANCAR', 'level' => 1, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '1011', 'parent_code' => '101', 'name' => 'KAS', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10111', 'parent_code' => '1011', 'name' => 'KAS TUNAI', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '10112', 'parent_code' => '1011', 'name' => 'KAS KASIR', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => 'kas_kasir', 'is_active' => true],
            ['code' => '10113', 'parent_code' => '1011', 'name' => 'KAS KECIL', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '1012', 'parent_code' => '101', 'name' => 'BANK', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10121', 'parent_code' => '1012', 'name' => 'BANK MANDIRI', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '10122', 'parent_code' => '1012', 'name' => 'BANK CIMB NIAGA', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10123', 'parent_code' => '1012', 'name' => 'BANK LAIN 2', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1013', 'parent_code' => '101', 'name' => 'INVESTASI', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10131', 'parent_code' => '1013', 'name' => 'REKSADANA', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10132', 'parent_code' => '1013', 'name' => 'PINTU', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10133', 'parent_code' => '1013', 'name' => 'DEPOSITO', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10134', 'parent_code' => '1013', 'name' => 'INVESTASI LAINNYA', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1014', 'parent_code' => '101', 'name' => 'PIUTANG', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10141', 'parent_code' => '1014', 'name' => 'PIUTANG DEVISI STORE MAKASSAR', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10142', 'parent_code' => '1014', 'name' => 'PIUTANG DEVISI STORE PALOPO', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10143', 'parent_code' => '1014', 'name' => 'PIUTANG DEVISI ROASTERY', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10144', 'parent_code' => '1014', 'name' => 'PIUTANG DEVISI RND', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10145', 'parent_code' => '1014', 'name' => 'PIUTANG DEVISI LALLO', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10146', 'parent_code' => '1014', 'name' => 'PIUTANG DEVISI HELLO', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10147', 'parent_code' => '1014', 'name' => 'PIUTANG PENJUALAN', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => 'piutang_elektronik', 'is_active' => true],
            ['code' => '10148', 'parent_code' => '1014', 'name' => 'PIUTANG LABA', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10149', 'parent_code' => '1014', 'name' => 'PIUTANG KARYAWAN', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '10150', 'parent_code' => '1015', 'name' => 'PIUTANG LAIN-LAIN', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '1015', 'parent_code' => '101', 'name' => 'UANG MUKA', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10151', 'parent_code' => '1015', 'name' => 'UANG MUKA PEMBELIAN AKTIVA', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10152', 'parent_code' => '1015', 'name' => 'UANG MUKA PEMBELIAN LAIN-LAIN', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10153', 'parent_code' => '1015', 'name' => 'UANG MUKA SEWA TEMPAT', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1016', 'parent_code' => '101', 'name' => 'PAJAK DIBAYAR DIMUKA', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10161', 'parent_code' => '1016', 'name' => 'PPH 21', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10162', 'parent_code' => '1016', 'name' => 'PPH 23', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10163', 'parent_code' => '1016', 'name' => 'PPH FINAL', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10164', 'parent_code' => '1016', 'name' => 'PPH 25', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1017', 'parent_code' => '101', 'name' => 'BEBAN DIBAYAR DIMUKA', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10171', 'parent_code' => '1017', 'name' => 'SEWA TEMPAT', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10172', 'parent_code' => '1017', 'name' => 'ASURANSI', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1018', 'parent_code' => '101', 'name' => 'INVESTASI JANGKA PANJANG', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10181', 'parent_code' => '1018', 'name' => 'PENYERTAAN SAHAM', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10182', 'parent_code' => '1018', 'name' => 'OBLIGASI', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10183', 'parent_code' => '1018', 'name' => 'INVESTASI PROPERTI', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1019', 'parent_code' => '101', 'name' => 'PERSEDIAAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10191', 'parent_code' => '1019', 'name' => 'PERSEDIAAN BAHAN BAKU', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => 'persediaan_bahan_baku', 'is_active' => true],
            ['code' => '10192', 'parent_code' => '1019', 'name' => 'PERSEDIAAN BAHAN SETENGAH JADI', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10193', 'parent_code' => '1019', 'name' => 'PERSEDIAAN PRODUK JADI', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10194', 'parent_code' => '1019', 'name' => 'PERSEDIAAN BAHAN PENDUKUNG', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '102', 'parent_code' => null, 'name' => 'ASET TETAP', 'level' => 1, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '1021', 'parent_code' => '102', 'name' => 'TANAH', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10211', 'parent_code' => '1021', 'name' => 'TANAH 1', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10212', 'parent_code' => '1021', 'name' => 'TANAH 2', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1022', 'parent_code' => '102', 'name' => 'BANGUNAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10221', 'parent_code' => '1022', 'name' => 'BANGUNAN 1', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10222', 'parent_code' => '1022', 'name' => 'BANGUNAN 2', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1023', 'parent_code' => '102', 'name' => 'KENDARAAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10231', 'parent_code' => '1023', 'name' => 'KENDARAAN 1', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10232', 'parent_code' => '1023', 'name' => 'KENDARAAN 2', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1024', 'parent_code' => '102', 'name' => 'PERALATAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10241', 'parent_code' => '1024', 'name' => 'PERALATAN', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '10242', 'parent_code' => '1024', 'name' => 'PERALATAN LAIN-LAIN', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '103', 'parent_code' => null, 'name' => 'AKUMULASI PENYUSUTAN ASET TETAP', 'level' => 1, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '1031', 'parent_code' => '103', 'name' => 'AKUMULASI PENYUSUTAN TANAH', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10311', 'parent_code' => '1031', 'name' => 'AKUMULASI PENYUSUTAN TANAH 1', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10312', 'parent_code' => '1031', 'name' => 'AKUMULASI PENYUSUTAN TANAH 2', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1032', 'parent_code' => '103', 'name' => 'AKUMULASI PENYUSUTAN BANGUNAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10321', 'parent_code' => '1032', 'name' => 'AKUMULASI PENYUSUTAN BANGUNAN 1', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10322', 'parent_code' => '1032', 'name' => 'AKUMULASI PENYUSUTAN BANGUNAN 1', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1033', 'parent_code' => '103', 'name' => 'AKUMULASI PENYUSUTAN KENDARAAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10331', 'parent_code' => '1033', 'name' => 'AKUMULASI PENYUSUTAN KENDARAAN 1', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10332', 'parent_code' => '1033', 'name' => 'AKUMULASI PENYUSUTAN KENDARAAN 2', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1034', 'parent_code' => '103', 'name' => 'AKUMULASI PENYUSUTAN PERALATAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10341', 'parent_code' => '1034', 'name' => 'AKUMULASI PENYUSUTAN PERALATAN 1', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '10342', 'parent_code' => '1034', 'name' => 'AKUMULASI PENYUSUTAN PERALATAN 2', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '104', 'parent_code' => null, 'name' => 'ASET TIDAK BERWUJUD', 'level' => 1, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '1041', 'parent_code' => '104', 'name' => 'HAK PATEN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10411', 'parent_code' => '1041', 'name' => 'HAK PATEN', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1042', 'parent_code' => '104', 'name' => 'MERK DAN CAP DAGANG', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10421', 'parent_code' => '1042', 'name' => 'MERK DAN CAP DAGANG', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1043', 'parent_code' => '104', 'name' => 'GOODWILL', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10431', 'parent_code' => '1043', 'name' => 'GOODWILL', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1044', 'parent_code' => '104', 'name' => 'FRANCHISE', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10441', 'parent_code' => '1044', 'name' => 'FRANCHISE', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '105', 'parent_code' => null, 'name' => 'ASET LAIN-LAIN', 'level' => 1, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '1051', 'parent_code' => '105', 'name' => 'BEBAN PRA OPERASI', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10511', 'parent_code' => '1051', 'name' => 'BEBAN PRA OPERASI', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1052', 'parent_code' => '105', 'name' => 'UANG JAMINAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10521', 'parent_code' => '1052', 'name' => 'UANG JAMINAN', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1053', 'parent_code' => '105', 'name' => 'AKTIVA TETAP YANG TIDAK DIGUNAKAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10531', 'parent_code' => '1053', 'name' => 'AKTIVA TETAP YANG TIDAK DIGUNAKAN', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '1054', 'parent_code' => '105', 'name' => 'LAINNYA', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '10541', 'parent_code' => '1054', 'name' => 'LAINNYA', 'level' => 3, 'account_type' => 'aset', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '201', 'parent_code' => null, 'name' => 'KEWAJIBAN LANCAR', 'level' => 1, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '2011', 'parent_code' => '201', 'name' => 'HUTANG  BEBAN OPERASIONAL DEVISI STORE MAKASSAR', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '20111', 'parent_code' => '2011', 'name' => 'HUTANG BEBAN GAJI POKOK', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20112', 'parent_code' => '2011', 'name' => 'HUTANG BEBAN TUNJANGAN JABATAN', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20113', 'parent_code' => '2011', 'name' => 'HUTANG BEBAN UANG MAKAN', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20114', 'parent_code' => '2011', 'name' => 'HUTANG BEBAN UANG HARIAN', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20115', 'parent_code' => '2011', 'name' => 'HUTANG BEBAN INSENTIF', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20116', 'parent_code' => '2011', 'name' => 'HUTANG BEBAN BONUS ABSENSI', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20117', 'parent_code' => '2011', 'name' => 'HUTANG BEBAN TUNJANGAN KELUARGA', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20118', 'parent_code' => '2011', 'name' => 'HUTANG BEBAN BPJS KESEHATAN', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '20119', 'parent_code' => '2011', 'name' => 'HUTANG BEBAN JHT', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '20120', 'parent_code' => '2012', 'name' => 'HUTANG BEBAN BONUS HARI RAYA', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20121', 'parent_code' => '2012', 'name' => 'HUTANG BEBAN BONUS TARGET', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20122', 'parent_code' => '2012', 'name' => 'HUTANG BEBAN BONUS TAHUNAN', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '20123', 'parent_code' => '2012', 'name' => 'HUTANG BEBAN KOMISI', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '2017', 'parent_code' => '201', 'name' => 'HUTANG DAGANG', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '20171', 'parent_code' => '2017', 'name' => 'HUTANG PEMBELIAN', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20172', 'parent_code' => '2017', 'name' => 'HUTANG BOP', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => 'hutang_bop', 'is_active' => true],
            ['code' => '20173', 'parent_code' => '2017', 'name' => 'HUTANG UANG MUKA PENJUALAN', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20174', 'parent_code' => '2017', 'name' => 'HUTANG JANGKA PENDEK LAIN-LAIN', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => 'hutang_lain_lain', 'is_active' => true],
            ['code' => '203', 'parent_code' => null, 'name' => 'KEWAJIBAN TIDAK LANCAR', 'level' => 1, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '2031', 'parent_code' => '203', 'name' => 'HUTANG JANGKA PANJANG', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '20131', 'parent_code' => '2013', 'name' => 'HUTANG PT. SOFIKOPI GROUP INDONESIA', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20132', 'parent_code' => '2013', 'name' => 'HUTANG PIHAK KETIGA', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '20133', 'parent_code' => '2013', 'name' => 'HUTANG BANK JANGKA PANJANG', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '20134', 'parent_code' => '2013', 'name' => 'HUTANG JANGKA PANJANG LAIN-LAIN', 'level' => 3, 'account_type' => 'kewajiban', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '301', 'parent_code' => null, 'name' => 'MODAL', 'level' => 1, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '3011', 'parent_code' => '301', 'name' => 'MODAL PERUSAHAAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '30111', 'parent_code' => '3011', 'name' => 'MODAL PT.SOFIKOPI GROUP INDONESIA', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '30112', 'parent_code' => '3011', 'name' => 'MODAL INVESTOR', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '30113', 'parent_code' => '3011', 'name' => 'MODAL PIHAK KETIGA', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '30114', 'parent_code' => '3011', 'name' => 'TAMBAHAN MODAL DISETOR', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '302', 'parent_code' => null, 'name' => 'DEVIDEN', 'level' => 1, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '3021', 'parent_code' => '302', 'name' => 'DEVIDEN DIREKSI', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '30211', 'parent_code' => '3021', 'name' => 'DEVIDEN PT. SOFIKOPI GROUP INDONESIA', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '30212', 'parent_code' => '3021', 'name' => 'DEVIDEN KCP', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '303', 'parent_code' => null, 'name' => 'LABA', 'level' => 1, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '3031', 'parent_code' => '303', 'name' => 'LABA BERJALAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '30311', 'parent_code' => '3031', 'name' => 'SALDO LABA SEBELUMNYA', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '30312', 'parent_code' => '3031', 'name' => 'KOREKSI SALDO LABA', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '30313', 'parent_code' => '3031', 'name' => 'SALDO LABA BERJALAN', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '3032', 'parent_code' => '303', 'name' => 'PEMECAHAN LABA', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '30321', 'parent_code' => '3032', 'name' => 'SAVING MODAL', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '30322', 'parent_code' => '3032', 'name' => 'ZAKAT', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '30323', 'parent_code' => '3032', 'name' => 'PAJAK', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '3033', 'parent_code' => '303', 'name' => 'PRIVE', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '30331', 'parent_code' => '3033', 'name' => 'PRIVE', 'level' => 3, 'account_type' => 'modal', 'position' => 'neraca', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '401', 'parent_code' => null, 'name' => 'LABA & RUGI', 'level' => 1, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '4011', 'parent_code' => '401', 'name' => 'PENDAPATAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '40111', 'parent_code' => '4011', 'name' => 'PENJUALAN', 'level' => 3, 'account_type' => 'pendapatan', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => 'penjualan', 'is_active' => true],
            ['code' => '40112', 'parent_code' => '4011', 'name' => 'PENDAPATAN JASA', 'level' => 3, 'account_type' => 'pendapatan', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40113', 'parent_code' => '4011', 'name' => 'PENDAPATAN BUNGA', 'level' => 3, 'account_type' => 'pendapatan', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40114', 'parent_code' => '4011', 'name' => 'PENDAPATAN LAIN-LAIN', 'level' => 3, 'account_type' => 'pendapatan', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40115', 'parent_code' => '4011', 'name' => 'PENDAPATAN LABA', 'level' => 3, 'account_type' => 'pendapatan', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '4012', 'parent_code' => '401', 'name' => 'HARGA POKOK PENJUALAN', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '40121', 'parent_code' => '4012', 'name' => 'HARGA POKOK PENJUALAN', 'level' => 3, 'account_type' => 'hpp', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => 'harga_pokok_penjualan', 'is_active' => true],
            ['code' => '4013', 'parent_code' => '401', 'name' => 'BIAYA ADM & UMUM', 'level' => 2, 'account_type' => null, 'position' => null, 'is_postable' => false, 'system_role' => null, 'is_active' => false],
            ['code' => '40131', 'parent_code' => '4013', 'name' => 'BEBAN GAJI POKOK', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40132', 'parent_code' => '4013', 'name' => 'BEBAN TUNJANGAN JABATAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40133', 'parent_code' => '4013', 'name' => 'BEBAN UANG MAKAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40134', 'parent_code' => '4013', 'name' => 'BEBAN UANG HARIAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40135', 'parent_code' => '4013', 'name' => 'BEBAN INSENTIF', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40136', 'parent_code' => '4013', 'name' => 'BEBAN BONUS ABSENSI', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40137', 'parent_code' => '4013', 'name' => 'BEBAN TUNJANGAN KELUARGA', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40138', 'parent_code' => '4013', 'name' => 'BEBAN BPJS KESEHATAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '40139', 'parent_code' => '4013', 'name' => 'BEBAN JHT', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '40140', 'parent_code' => '4014', 'name' => 'BEBAN BONUS HARI RAYA', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40141', 'parent_code' => '4014', 'name' => 'BEBAN BONUS TARGET', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40142', 'parent_code' => '4014', 'name' => 'BEBAN BONUS TAHUNAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '40143', 'parent_code' => '4014', 'name' => 'BEBAN KOMISI', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => false],
            ['code' => '40144', 'parent_code' => '4014', 'name' => 'BEBAN PENYUSUTAN BAHAN BAKU', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40145', 'parent_code' => '4014', 'name' => 'BEBAN PENYUSUTAN BAHAN SETENGAH JADI', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40146', 'parent_code' => '4014', 'name' => 'BEBAN PENYUSUTAN BAHAN PENDUKUNG', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40147', 'parent_code' => '4014', 'name' => 'BIAYA PENDUKUNG PRODUKSI', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40148', 'parent_code' => '4014', 'name' => 'BEBAN SELISIH PERSEDIAAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40149', 'parent_code' => '4014', 'name' => 'BEBAN SELISIH PEMBELIAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40150', 'parent_code' => '4015', 'name' => 'BEBAN OVERHEAD PRODUKSI', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => 'beban_overhead_produksi', 'is_active' => true],
            ['code' => '40151', 'parent_code' => '4015', 'name' => 'BEBAN PRODUKSI LAIN-LAIN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40152', 'parent_code' => '4015', 'name' => 'BIAYA PERBAIKAN & PERAWATAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40153', 'parent_code' => '4015', 'name' => 'BIAYA TENAGA KERJA LANGSUNG', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40154', 'parent_code' => '4015', 'name' => 'BEBAN SELISIH PENJUALAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40155', 'parent_code' => '4015', 'name' => 'BIAYA PENDUKUNG PENJUALAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40156', 'parent_code' => '4015', 'name' => 'BIAYA PENGIRIMAN / PENGANTARAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40157', 'parent_code' => '4015', 'name' => 'BIAYA IKLAN & PROMOSI', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40158', 'parent_code' => '4015', 'name' => 'BIAYA GAS', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40159', 'parent_code' => '4015', 'name' => 'BIAYA LISTRIK', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40160', 'parent_code' => '4016', 'name' => 'BIAYA AIR', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40161', 'parent_code' => '4016', 'name' => 'BIAYA WIFI', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40162', 'parent_code' => '4016', 'name' => 'BIAYA BENSIN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40163', 'parent_code' => '4016', 'name' => 'BIAYA TRANSPORTASI', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40164', 'parent_code' => '4016', 'name' => 'BIAYA KOMUNIKASI', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40165', 'parent_code' => '4016', 'name' => 'BIAYA KONSUMSI', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40166', 'parent_code' => '4016', 'name' => 'BIAYA ENTERTAIN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40167', 'parent_code' => '4016', 'name' => 'BIAYA ADMINISTRASI BANK', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => 'beban_admin_bank', 'is_active' => true],
            ['code' => '40168', 'parent_code' => '4016', 'name' => 'BIAYA SOSIAL', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40169', 'parent_code' => '4016', 'name' => 'BIAYA LAIN-LAIN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40170', 'parent_code' => '4017', 'name' => 'BEBAN WESEL', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40171', 'parent_code' => '4017', 'name' => 'BEBAN PENYUSUTAN BANGUNAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40172', 'parent_code' => '4017', 'name' => 'BEBAN PENYUSUTAN KENDARAAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
            ['code' => '40173', 'parent_code' => '4017', 'name' => 'BEBAN PENYUSUTAN PERALATAN', 'level' => 3, 'account_type' => 'biaya_adm_umum', 'position' => 'laba_rugi', 'is_postable' => true, 'system_role' => null, 'is_active' => true],
        ];
    }
}
